CREATE TABLE game_logs(
	split integer,
	date date,
	game integer,
	player_id integer,
	position varchar(2),
	team_id smallint,
	opp_id smallint,
	isHome bool,
	isWin bool,
	isOT bool,
	fws smallint,
	assists smallint,
	goals smallint,
	pim smallint,
	shots smallint,
	hits smallint,
	powerPlayPoints smallint,
	shortHandedPoints smallint,
	powerPlayTimeOnIce varchar(8),
	evenTimeOnIce varchar(8),
	shortHandedTimeOnIce varchar(8),
	gameWinningGoals smallint,
	blocked smallint,
	plusMinus smallint,
	shifts smallint,
	shutouts smallint,
	saves smallint,
	shortHandedShots smallint,
	evenShots smallint,
	powerPlayShots smallint,
	goalsAgainst smallint,
	fanpts double precision
);